version: '3.8'

volumes:
  db-volume:

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./src/:/var/www/html
    environment:
      - DB_HOST=db
      - DB_USERNAME=my_user
      - DB_DATABASE=my_database
      - DB_PASSWORD=my_password
#      - DB_CONNECTION=mysql
#      - DB_HOST=db
#      - DB_PORT=3306
#      - DB_DATABASE=${DB_NAME}
#      - DB_USERNAME=${DB_USER}
#      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - app
    volumes:
      - ./src/:/var/www/html

  db:
    image: docker.io/bitnami/mariadb:10.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      - MARIADB_PASSWORD=my_password

    volumes:
      - db-volume:/var/lib/mysql
#  db:
#    build:
#      context: .
#      dockerfile: ./docker/mysql/Dockerfile
#    ports:
#      - ${DB_PORT}:3306
#    environment:
#      MYSQL_DATABASE: ${DB_NAME}
#      MYSQL_USER: ${DB_USER}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
#      TZ: 'Asia/Tokyo'
#    volumes:
#      - db-volume:/var/lib/mysql
